---
apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: e2e-tests
          image: eu.gcr.io/argo-prototype-1/e2e-tests:master
          command: ["run"]
      restartPolicy: Never
  backoffLimit: 0