apiVersion: v1
data:
  accounts.argonaut: apiKey, login
  admin.enabled: "false"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"admin.enabled":"false"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2021-11-04T16:41:58Z","labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd","resourceVersion":"11892","uid":"2c3a3d45-ce87-482c-bc7d-2d583cd381b6"}}
  creationTimestamp: "2021-11-04T16:41:58Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "17035"
  uid: 2c3a3d45-ce87-482c-bc7d-2d583cd381b6
